set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME iOS)
set(VCPKG_CMAKE_CONFIGURE_OPTIONS
    "-DCMAKE_OSX_SYSROOT=iphonesimulator"
    "-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64"
)

set(VCPKG_BUILD_TYPE release)