set(VCPKG_TARGET_ARCHITECTURE arm64 x86_64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME iOS)
set(VCPKG_OSX_SYSROOT iphonesimulator)

set(VCPKG_CMAKE_CONFIGURE_OPTIONS -DCMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH=OFF -DCMAKE_IOS_INSTALL_COMBINED=ON)
set(VCPKG_BUILD_TYPE release)
